config/routes.rb
Rails.application.routes.draw do

 root 'pages#welcome'

 get '/portfolio' => 'pages#portfolio'
 get '/about' => 'pages#about'
 get '/contact' => 'pages#contact'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  
  def portfolio
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  
  <!-- font styles -->
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,500,700' rel='stylesheet' type='text/css'>

  <!-- bootstrap -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Font Awesome -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  
    <!-- Twitter Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<<<<<<< HEAD

=======
   <!-- Font Awesome -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
>>>>>>> a66a929c44a4211de94a57565d20eb5e6da242a7
</head>
  
  
<body>
	<!-- Fixed navbar -->
  
    <nav class="navbar navbar-default" role="navigation">

        <div id="navbar">
          <ul class="nav navbar-nav">       
            <li><%= link_to "Welcome Page", "/" %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Portfolio", portfolio_path %></li>
            <li><%= link_to "Contact Page", contact_path %></li>
          </ul>
        </div>
        
    </nav> 
  
<%= yield %>

  <footer class="footer">    
	  <div class="container">

	    	<p class="text-muted">&copy; 2015 Kai Kuroda</p>
      
        <p class="social-icons">
        	<a href="mailto:kkuroda27@gmail.com"><i class="fa fa-envelope fa-3x"></i></a>            
        	<a href="http://www.github.com/kkuroda27"><i class="fa fa-github fa-3x"></i></a>        
       	  <a href="http://www.linkedin.com/in/kaitokuroda"><i class="fa fa-linkedin fa-3x"></i></a>               		
      </p>
	  </div>
	</footer>
  

</body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<div class="image-grid grid_1">
		<%= image_tag "" %><%= image_tag "" %>
	</div>
	<div class="about-text">
		<h3 class="about-heading">About Me</h3>
		<p>This is a </p>
		<p>Description </p>
		<p>Of me </p>
	</div>
	<div class="image-grid grid_2">
		<%= image_tag "" %><%= image_tag "" %>
	</div>
	
</div>

app/views/pages/contact.html.erb
<div class="jumbotron jumbotron-sm">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <h1 class="h1">Contact Me</h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="well well-sm">
                <form>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name"> Name</label>
                            <input type="text" class="form-control" id="name" placeholder="Enter name" required="required" />
                        </div>
                        <div class="form-group">
                            <label for="email"> Email Address</label>
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                                </span>
                                <input type="email" class="form-control" id="email" placeholder="Enter email" required="required" /></div>
                        </div>
                        <div class="form-group">
                            <label for="subject"> Subject</label>
                            <select id="subject" name="subject" class="form-control" required="required">
                                <option value="na" selected="">Choose One:</option>
                                <option value="job">Job Opportunity</option>
                                <option value="freelance">Freelance Bid</option>
                                <option value="creative">Creative Collaboration</option>
                                <option value="hi">Just Saying Hi</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name"> Message</label>
                            <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                                placeholder="Message"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">
                            Send Message</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <form>
                <legend><span class="glyphicon glyphicon-globe"></span> On the Web</legend>
                <address>
                    <p><a href="mailto:kkuroda27@gmail.com"><i class="fa fa-envelope"></i>Email</a></p>
    	    		<p><a href="http://www.github.com/kkuroda27"><i class="fa fa-github"></i>Github</a></p>
    	    		<p><a href="http://www.linkedin.com/in/kaitokuroda"><i class="fa fa-linkedin"></i>LinkedIn</a></p>

                        Phone:</abbr>
                    (985) 264-8472
                </address>
                <address>
                    <strong>Email:</strong><br>
                    <a href="mailto:kkuroda27@gmail.com">kkuroda27@gmail.com</a>
                </address>
            </form>
        </div>
    </div>
</div>

app/views/pages/portfolio.html.erb
<div class="container">
	<h1>Portfolio</h1>
</div>
    
<div class="banner">
      <ul>

      <li><%= image_tag("http://s4.postimg.org/vmrvwyv25/Screen_Shot_2015_09_29_at_8_30_42_PM.png", :size => "780x540") %></li>
      <li><%= image_tag("http://s23.postimg.org/gh2cj9n2z/Screen_Shot_2015_09_29_at_8_30_33_PM.png", :size => "780x540") %></li>
      <li><%= image_tag("http://s4.postimg.org/vmrvwyv25/Screen_Shot_2015_09_29_at_8_30_42_PM.png", :size => "780x540") %></li>

      </ul>
      
</div>

<div class="supporting">
  <div class="container">

    <div class="row">
      <% 
=begin %>
      <% @works.each do |work| %>
      <div class="col-md-4">
        <a class="thumbnail" href="#">
          <h3><%= work.name %></h3>
          <p><%= image_tag("../assets/website-screenshots/#{work.imgurl}.png", class: "img-responsive") %></p>
          <p><%= work.description %></p>
        </a>
      </div>    
      <% end %>
      <% 
=end %>

    </div>
    
  </div>
</div>

app/views/pages/welcome.html.erb
<div class="site-wrapper">

  <div class="site-wrapper-inner">

    <div class="container">

      <div class="inner cover">
        <h1 class="cover-heading">Hi, I'm <span class="name">Kai</span>!</h1>
        <h2>I create unique and awesome web experiences 		        </h2>
        <%= link_to "View My Portfolio", portfolio_path, class: "btn btn-lg btn-default"%>
      </div>

    </div>

  </div>

</div>